### ISSUE TITLE
Uzun kod yazmisiz amma neticesindede duzgun cavab gorsedilmir.Bele kod yazmaga calismaxinizi alqishlayiram.List metodlarini arasdirin,tekce bir metodla listi tersine ekrana yazdirmaq mumkundur

### ISSUE THREAD

**Issue by Ferid-Memmedli** [eljn0/Python-archieve#1]
https://github.com/eljn0/PragmatechFoundationProject/blob/ca3859b7c861e2fde5c881bb1e081524e6c76135/python%20tasks/task7.py#L1

**Comment by eljn0** [comment]
Salam ,
Duzdu uzun kod yazmisam ama bu menim progressim ucundue feedback ucun
tesekkur edirem

21 fev 2021, B. tarixində 13:07 tarixində Ferid Memmedli <
notifications@github.com> yazdı:
